### ISSUE TITLE
dict object' has no attribute 'galera-cluster-nodes

### ISSUE THREAD

**Issue by zaraquer** [mrlesmithjr/ansible-mariadb-galera-cluster#127]
Hi!

I'm new in ansible, and I try to install a galera cluster on my test enviroment. But I have this error:

Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible/template/__init__.py", line 1096, in do_template
    res = self.environment.concat(rf)
  File "/usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible/template/native_helpers.py", line 70, in ansible_eval_concat
    head = list(islice(nodes, 2))
  File "<template>", line 16, in root
  File "/usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'galera-cluster-nodes'

I tried to find out what was the problem, but I wont find this variable anywhere.

Ansible version:
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/Users/imagyar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/imagyar/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True

playbook.yml:
---
- name: Example Playbook
  hosts: all
  tasks:
    - name: Include ansible-mariadb-galera-cluster
      include_role:
        name: mrlesmithjr.mariadb_galera_cluster

Thanks!

**Comment by eRadical** [comment]
Hello @zaraquer,

You need to overwrite the value from defaults named `galera_cluster_nodes_group` and use there the actual name of the group where the galera cluster should be installed.

My galera cluster override file is something along these lines:

```
---
galera_cluster_bind_interface: 'eth0'  # make sure this interface exists in your servers
# yamllint disable-line rule:line-length
galera_cluster_name: 'clients_mariadb_gc_staging'  # this name should be under 32 chars or galera cluster will not start
galera_cluster_nodes_group: 'clients_mariadb_galera_cluster'  ## this is the most important one
mariadb_version: '10.6'
mariadb_mysql_root_password: "some-password"

```

**Comment by zaraquer** [comment]
Hi @eRadical !

Thanks for your comment!
I already named it after the group name in my inventory file.

# Define the name of the cluster
galera_cluster_name: "galera-test"

# Define Ansible group in which the nodes exist to be part of the cluster
galera_cluster_nodes_group: "mariadb"

Inventory file:
[mariadb]
mariadb1 ansible_host=xxx.xxx.xxx.51
mariadb2 ansible_host=xxx.xxx.xxx.52
mariadb3 ansible_host=xxx.xxx.xxx.53

[all:vars]
ansible_python_interpreter=/usr/bin/python3

**Comment by eRadical** [comment]
@zaraquer  - any progress on this?

Can you pase a file with ansible-playbook run with "-vvvv" ?

**Comment by zaraquer** [comment]
@eRadical 

Sure, I can paste, this is the error I get, and I still stuck here.:

```
TASK [mrlesmithjr.mariadb_galera_cluster : ensure mariadb is started on first node] **********************************************************************************************************************************************************
task path: /root/.ansible/roles/mrlesmithjr.mariadb_galera_cluster/tasks/main.yml:40
fatal: [mariadb1]: FAILED! => {
    "msg": "The conditional check 'inventory_hostname == galera_mysql_first_node' failed. The error was: error while evaluating conditional (inventory_hostname == galera_mysql_first_node): 'dict object' has no attribute 'galera-cluster-nodes'\n\nThe error appears to be in '/root/.ansible/roles/mrlesmithjr.mariadb_galera_cluster/tasks/main.yml': line 40, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# ensure the first node is running in order to add users\n- name: \"ensure {{ mariadb_systemd_service_name }} is started on first node\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}
fatal: [mariadb2]: FAILED! => {
    "msg": "The conditional check 'inventory_hostname == galera_mysql_first_node' failed. The error was: error while evaluating conditional (inventory_hostname == galera_mysql_first_node): 'dict object' has no attribute 'galera-cluster-nodes'\n\nThe error appears to be in '/root/.ansible/roles/mrlesmithjr.mariadb_galera_cluster/tasks/main.yml': line 40, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# ensure the first node is running in order to add users\n- name: \"ensure {{ mariadb_systemd_service_name }} is started on first node\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}
fatal: [mariadb3]: FAILED! => {
    "msg": "The conditional check 'inventory_hostname == galera_mysql_first_node' failed. The error was: error while evaluating conditional (inventory_hostname == galera_mysql_first_node): 'dict object' has no attribute 'galera-cluster-nodes'\n\nThe error appears to be in '/root/.ansible/roles/mrlesmithjr.mariadb_galera_cluster/tasks/main.yml': line 40, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# ensure the first node is running in order to add users\n- name: \"ensure {{ mariadb_systemd_service_name }} is started on first node\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}
```

**Comment by zaraquer** [comment]
@eRadical 

I have some progress, but I still stuck in here:

```
TASK [mrlesmithjr.mariadb_galera_cluster : Check if mysql exists in the system] **************************************************************************************************************************************************************
task path: /root/.ansible/roles/mrlesmithjr.mariadb_galera_cluster/tasks/mysql_users.yml:5
fatal: [mariadb1]: FAILED! => {
    "msg": "'dict object' has no attribute 'galera-cluster-nodes'"
}
...ignoring

TASK [mrlesmithjr.mariadb_galera_cluster : Fail if the above user does not exist] ************************************************************************************************************************************************************
task path: /root/.ansible/roles/mrlesmithjr.mariadb_galera_cluster/tasks/mysql_users.yml:11
fatal: [mariadb1]: FAILED! => {
    "msg": "'dict object' has no attribute 'galera-cluster-nodes'"
}
```

Do you have any idea what I miss? Thanks!

**Comment by zaraquer** [comment]
@eRadical 

Hi!

I figured out, there was a missing quote in the main.yml and needed to change some values. It seems it solved now.

**Comment by eRadical** [comment]
Glad you sorted it out.
