### ISSUE TITLE
No package matching 'python-pymysql' is available

### ISSUE THREAD

**Issue by RomainL972** [mrlesmithjr/ansible-mariadb-galera-cluster#129]
**Describe the bug**
At the step "mrlesmithjr.mariadb_galera_cluster : debian | installing pre-reqs", the installation fails because it tries to install the apt package python-pymysql which doesn't exist on Ubuntu 22.04 LTS.

**To Reproduce**
1. Install the role mrlesmithjr.mariadb_galera_cluster on a Ubuntu 22.04 LTS host
2. Wait until step "mrlesmithjr.mariadb_galera_cluster : debian | installing pre-reqs" is executed
3. See error

**Expected behavior**
The `python-pymysql` package should not be installed on Ubuntu 22.04 hosts

**Screenshots**
![image](https://user-images.githubusercontent.com/24463530/189134876-0e1b3d3f-176e-41b5-86d9-b06aa2b5c916.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS

**Comment by eRadical** [comment]
Hm... interesting.
There is "python3-pymysql" for Ubuntu 22*.

**Comment by RomainL972** [comment]
I think the problem is that there is no "ubuntu-22.yml" file in vars, so it takes the "mariadb_pre_req_packages" variable from vars/debian.yml

**Comment by eRadical** [comment]
This is in #126.

**Comment by eRadical** [comment]
Fixed by #126
