### ISSUE TITLE
Can't find any matching row in the user table

### ISSUE THREAD

**Issue by eRadical** [mrlesmithjr/ansible-mariadb-galera-cluster#131]
**Describe the bug**
With new version of ansible and community mysql I started getting the following error:

```
failed: [services-mariadb-cluster-01.staging.example.com] (item=ip-172-21-1-53) => {"ansible_loop_var": "item", "changed": false, "item": "ip-172-21-1-53", "msg": "(1133, \"Can't find any matching row in the user table\")"}
ok: [services-mariadb-cluster-01.staging.example.com] => (item=127.0.0.1)
ok: [services-mariadb-cluster-01.staging.example.com] => (item=::1)
ok: [services-mariadb-cluster-01.staging.example.com] => (item=localhost)
```

**To Reproduce**
community.mysql   3.5.1 

**Expected behavior**
Either ignore or cleanup `root` accounts and keep only the `localhost` one.

**Additional context**
To get past my reconfiguration I added:
```
ignore_errors: true
```
but I not sure if we can keep this or came up w/ a better solution.

**Comment by kwizart** [comment]
I've experienced this error while having mariadb using skip_name_resolve = 1 and "{{ ansible_hostname }}" case started failing. I think removing this item might be safe.


Side note, ignore-errors is leading to errors in pre-commit .  So it might be wise to rework this issue...
