### ISSUE TITLE
Documentation for setting variables

### ISSUE THREAD

**Issue by perpi** [mrlesmithjr/ansible-mariadb-galera-cluster#133]
There's no guide for customizing variables per our environment. For example, I got an error for the interface, and then I understood that I should go to `main.yml` to replace the interface name (eth0) with mine (which is ens160 by default in Ubuntu).

May you document the required variables to be replaced? Thanks

**Comment by eRadical** [comment]
I'll try to set some time aside to pipmp up the [README.md].
