### ISSUE TITLE
MariaDB repositories moved

### ISSUE THREAD

**Issue by elcomtik** [mrlesmithjr/ansible-mariadb-galera-cluster#135]
**Describe the bug**
As I'm working on https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/pull/134 I discovered an issue with current MariaDB package mirror URL used in templates/tasks. It looks like they deprecated old URLs in favor of new ones. Also, they introduced some [MariaDB Package Repository setup script](https://mariadb.com/kb/en/mariadb-package-repository-setup-and-usage/), which configures URLs like this one https://dlm.mariadb.com/repo/mariadb-server/10.6/yum/rhel/8/x86_64.

**To Reproduce**
run tests and it fails on installing package from MariaDB repository. You may see result in https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/actions/runs/3319905763/jobs/5485640462

**Comment by elcomtik** [comment]
@eRadical did you notice a similar issue? Should I fix that URL in the same PR mentioned above, to be able fix failing tests?

**Comment by eRadical** [comment]
Yes. Just noted. Sad change!

```
MariaDB                                                                                                                         31  B/s |  10  B     00:00    
Errors during downloading metadata for repository 'mariadb':
  - Status code: 404 for http://mirror.mariadb.org/yum/10.6/centos/8/x86_64/repodata/repomd.xml (IP: 162.55.42.214)
Error: Failed to download metadata for repo 'mariadb': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
Basically all our installs are stuck at the current version.
Not a great move from MariaDB. :(

**Comment by elcomtik** [comment]
I'm working on the fix, currently testing my code at my Rocky8 deployment. Soon I'll push code to PR https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/pull/134, to test other platforms, also.

**Comment by eRadical** [comment]
Also the `gpgkey` is not retrieved via https anymore.

**Comment by elcomtik** [comment]
I think it works with "https://supplychain.mariadb.com/MariaDB-Server-GPG-KEY", did you tried?

**Comment by elcomtik** [comment]
It's weird, looks like it was a temporary outage. Currently old repo URLs are working again

**Comment by eRadical** [comment]
Or maybe because I whined about it on Twitter...

**Comment by elcomtik** [comment]
oh, cool. could you put here the link for reference?

**Comment by eRadical** [comment]
https://twitter.com/eRadical/status/1584897313691955201

**Comment by elcomtik** [comment]
We will see if there will be a response from them

**Comment by eRadical** [comment]
In 10.6.11 release notes there is a note - https://mariadb.com/kb/en/mariadb-10-6-11-release-notes/#repositories but only mentions the change of the signing key.
