### ISSUE TITLE
[debian] `/etc/mysql/conf.d/overrides.cnf` Permissions Constantly Changing

### ISSUE THREAD

**Issue by sdwilsh** [mrlesmithjr/ansible-mariadb-galera-cluster#150]
**Describe the bug**
`/etc/mysql/conf.d/overrides.cnf` changes every time this is ran even if the contents change because another rule recursively updates the permissions of things in `/etc/mysql/conf.d`.

Here's where the code recurses and modifies all permissions:
https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/blob/853bca765916e1c25045cf29a23d672070306427/tasks/debian.yml#L45-L53

And here is where it then gets changed back to `0644`:
https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/blob/853bca765916e1c25045cf29a23d672070306427/tasks/debian.yml#L55-L61

**Expected behavior**
The step `debian | add an overrides file` shouldn't change with every invocation.  I'm not sure what the right fix is here, to be honest.  I think it might be safe to not recurse in this directory, and anyone adding their own files will just have to make sure the permissions are right.

**Comment by elcomtik** [comment]
I wondered why it didn't trigger idempotency checks in test, then I saw changed param set to false.

This should be fixed, would you like to make PR for this?

**Comment by sdwilsh** [comment]
I can.  Are you good with just not recursing the permissions change (and probably getting rid of the `changed_when: false`)?

**Comment by elcomtik** [comment]
LGTM

**Comment by elcomtik** [comment]
Would you please change it for redhat tasks as well?

**Comment by eRadical** [comment]
No `recurse` in redhat.

**Comment by sdwilsh** [comment]
Oh yikes...this also changes `/etc/mysql/conf.d/galera.cnf`, which means it's actually restarting the cluster every time this runs due to this bit:
https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/blob/2b344d7d25520e334d312f3bc09fb34c1bd1d2bd/tasks/setup_cluster.yml#L79-L87

I just discovered this little detail while debugging why my cluster was down.  I have a cron job that runs hourly to ensure state because things should be idempotent, and somehow it managed to kill off the whole cluster (I can see that this was the last thing that was logged by [ARA](https://ara.recordsansible.org/), which of course I've configured to use the cluster).

**Comment by elcomtik** [comment]
Unfortunate... It was direct consequence of bypassing idempotency tests. Neither I nor @eRadical use debian systems, so it wasn't discovered until you came. I will merge fix ASAP.

**Comment by elcomtik** [comment]
Just merged, feel free to test it.

**Comment by sdwilsh** [comment]
It worked before I submitted it, so I'm not too worried about re-testing :)

Is there a release schedule, or are releases ad-hoc?

**Comment by elcomtik** [comment]
I personally use code from master branch. There should be automatic release at start of every month.
