### ISSUE TITLE
Different interface naming on dedicated servers

### ISSUE THREAD

**Issue by madalinignisca** [mrlesmithjr/ansible-mariadb-galera-cluster#151]
**Describe the bug**
I'm trying to deploy on a cluster of dedicated servers. Although configuration is almost identical, I get on some servers interface name eno1 and others enp0s31f6.

galera_cluster_bind_interface

**To Reproduce**
1. Set `galera_cluster_bind_interface` to an interface identified on one of the servers
2. Try to run the playbook
3. Fails on first server with different network interface name

**Expected behavior**
I would expect to configure the cluster.

Hello.

I would love some hints on where to look on how to be able to build dynamically the `galera_wsrep_node_address` as on some servers I have eno1 and on others enp0s31f6. This is on servers with e1000e (Intel(R) PRO/1000 I219-V or I219-LM).

I have base Debian 11 installed on them, with no modifications, and some servers get eno1, some enp0s31f6, mixed between network cards, so it's not about the exact type.

I'd be happy if I'd find out quick how can I figure out in another way the value for `galera_wsrep_node_address`.

**Comment by elcomtik** [comment]
I would suggest to rename interfaces on all server in cluster to same name. 

I would prefer to keep this role as simple as possible and maintain Unix philosophy to do just one thing. 

I suppose that there are already some role which handles this tasks.

**Comment by elcomtik** [comment]
It should be done prior to applying this role, I found blogspot which shows how-to https://forty.sh/posts/2021-01-15-renaming-network-interfaces/

This can be made by few tasks, eg. in pre-task in playbook which is using this role.

**Comment by eRadical** [comment]
Maybe you can do:

**Comment by madalinignisca** [comment]
> rvices-mariadb-cluster-01.

Hi and thank you for the tip. Actually, this is precisely what I did last night, and it worked perfectly. I should have thought from the start.

**Comment by eRadical** [comment]
Glad it works for you.
