### ISSUE TITLE
Update `CONTRIBUTING.md` to contain steps to setup the environment

### ISSUE THREAD

**Issue by sdwilsh** [mrlesmithjr/ansible-mariadb-galera-cluster#153]
I didn't realize until after I submitted #152 that this project uses pre-commit.  I did check [`CONTRIBUTING.md`](https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/blob/master/CONTRIBUTING.md) before writing the PR, but didn't see anything in there.  It'd be great to have all the setup instructions here so folks can provide a better-verified PR prior to submitting it.

**Comment by elcomtik** [comment]
https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/blob/master/CONTRIBUTING.md is generated from a cookie-cutter template. Until now neither I nor @eRadical complained about the quality of the received PR.

Nobody can be forced to use pre-commit, it may be noted, but we can't be sure that the code is compliant until the Github action tests are done.

I'm not against modifying the instructions, feel free to submit your PR.
