### ISSUE TITLE
use community.mysql.mysql_user instead of mysql_user

### ISSUE THREAD

**Issue by AnthonyTissot** [mrlesmithjr/ansible-mariadb-galera-cluster#158]
Hi
in order to fix an issue  "unkown plugin option" during mysql user creation, is it possible to specify the ansible module to use for myql_user.
file : tasks/mysql_users.yml
 change proposal:
- name: mysql_users | create MySQL users
  **community.mysql.mysql_user**
Best regards and thank you for your work

**Comment by elcomtik** [comment]
I agree that we should do this change.

**Comment by eRadical** [comment]
Fixed w/ pull request #160
