### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by fjousseaume-ofemploi** [mrlesmithjr/ansible-mariadb-galera-cluster#16]
Hello,

Is it possible you create tag to set it in requirements.yml, your role is very interesting but we can not force a given version...

Thank you !

Florent,

**Comment by mrlesmithjr** [comment]
@fjousseaume-ofemploi I have created `v0.1.0` tag which you should be able to use now in your `requirements.yml`. Let me know if this does not work for you.

**Comment by mrlesmithjr** [comment]
Let me know if you still run into issues. I would need to spin up some CentOS 7 nodes for testing and see if I can duplicate the issue.

**Comment by fjousseaume-ofemploi** [comment]
I send you tomorrow log messages in a new issue.
