### ISSUE TITLE
python3 support for galeranotify.py

### ISSUE THREAD

**Issue by kwizart** [mrlesmithjr/ansible-mariadb-galera-cluster#167]
**Is your feature request related to a problem? Please describe.**
Modern distro doesn't provide python2 support by default and don't even have /usr/bin/python shebang

**Describe the solution you'd like**
Switch galeraynotify.py.j2 to use python3 syntax by default

**Describe alternatives you've considered**
I've ported the script to use python3, but it will break existing test case with distro using python2 by default (centos7 so far that is supported until 30 June 2024)

**Additional context**
I've ported the script to python3 which works fine in my case
https://github.com/kwizart/ansible-mariadb-galera-cluster/commit/be00edb021e30fb02a06b535ebcdf7c4be950c91

Now I need not to break existing users and use a "reasonable default" to have python3 in some case but python2 elsewhere...

What I can envision is:
- Have a separate galeranotify.py3.template
- Default to galeranotify.py3.template 
- Switch back to python2 version for : centos7, debian < x, ubuntu < y and explicitly set option...

**Comment by eRadical** [comment]
Hi @kwizart,

Your `vision` sounds very right to me!

Why not give it a try w/ a pull request for this?
I would review it immediately!

By the way... you should not care about distro or it's version. I would rather do it via:
```
- name: Install galeranotify.py for Python 2
  ...
  when: ansible_python.version.major|int == 2

- name: Install galeranotify.py for Python 3
  ...
  when: ansible_python.version.major|int == 3
```
... or something similar.

**Comment by kwizart** [comment]
Issue fixed, thanks !
