### ISSUE TITLE
Support RHEL 8

### ISSUE THREAD

**Issue by cmayer89** [mrlesmithjr/ansible-mariadb-galera-cluster#175]
I'm trying to deploy mariadb on rhel 8 but I'm running into the following error:

TASK [mrlesmithjr.mariadb-galera-cluster : redhat | installing pre-reqs] ***************************************************************************************************************************************
fatal: [mysql01.example.lan]: FAILED! => {"changed": false, "failures": ["MySQL-python No match for argument: MySQL-python"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
fatal: [mysql02.example.lan]: FAILED! => {"changed": false, "failures": ["MySQL-python No match for argument: MySQL-python"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
fatal: [mysql03.example.lan]: FAILED! => {"changed": false, "failures": ["MySQL-python No match for argument: MySQL-python"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

MySQL-python maybe python3-PyMySQL

The package MySQL-python is not available on RHEL 8. 

I believe that this can probably be resolved by adding a `redhat-8.yml` file to the vars directory and adjusting the values to match what is currently in the `centos-8.yml` vars file.

**Comment by eRadical** [comment]
Hi @cmayer89,

Would you mind adding a PR? I'll merge it.

**Comment by sglessard** [comment]
Hello,

We're encountering this on RHEL 9 and are curious about the current status. Is there a particular reason none of the proposed fixes have been accepted
I'm interested in moving forward with a potential resolution and would be happy to collaborate or help test a fix.

Our quick fix :

```
mariadb_pre_req_packages:
-     - "python3-mysqlclient"
```

Thanks
