### ISSUE TITLE
vars/centos-9.yml config file missing

### ISSUE THREAD

**Issue by kk-r1c** [mrlesmithjr/ansible-mariadb-galera-cluster#190]
Hello,

I am still using CentOS 8 Stream with your role and would like to upgrade to CentOS 9 Stream.

In the task 'gather os specific variables' a file name is built from *ansible_distribution* and *ansible_version* which would create a file called *centos-9.yml*.

Unfortunately in the vars directory it misses this config file which should have the same content as the *rocky-9.yml* file.

Is it possible to add it to the vars directory?

Thank you in advance.

**Comment by eRadical** [comment]
keep

**Comment by eRadical** [comment]
Merged but there is an incoming PR (#200) that modifies the file a little.
File might need update.
