### ISSUE TITLE
Permission of configuration files are harcoded

### ISSUE THREAD

**Issue by roumano** [mrlesmithjr/ansible-mariadb-galera-cluster#199]
**Describe the bug**
Actually on the file `setup_cluster.yml`, the permission is harcoded to `0644`

On debian, as exemple, the file /etc/mysql/debian.cnf is set to `0600`

So, it 's actually too open but even worse after a package update, the ansible role change roll-back the permission, so it's restart the galera cluster so it's not good for production server...

**To Reproduce**
1. `apt update ; apt upgrade`
2. execute the role on the cluster
3. Log output of the task `setup_cluster | configuring settings for mariadb and galera` :
```
{
  "diff": {
    "before": {
      "path": "/etc/mysql/debian.cnf",
      "mode": "0600"
    },
    "after": {
      "path": "/etc/mysql/debian.cnf",
      "mode": "0644"
    }
  },
  "path": "/etc/mysql/debian.cnf",
  "changed": true,
```

**Comment by eRadical** [comment]
Keep

**Comment by eRadical** [comment]
Keep

**Comment by eRadical** [comment]
keep

**Comment by eRadical** [comment]
Merged!
