### ISSUE TITLE
Cluster joining - serial?

### ISSUE THREAD

**Issue by eRadical** [mrlesmithjr/ansible-mariadb-galera-cluster#21]
https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/blob/7cf2f08c30a8865764bbd66a8f81634ddf9f2076/tasks/setup_cluster.yml#L86-L93

What do you think about adding `serial: 1` in here so ansible will do this host by host instead of all joining the cluster at once?

**Comment by mrlesmithjr** [comment]
Have you ran into issues with them all doing it at the same time? I have used this role a few times this past week without any issues. But definitely open to it if it makes sense.

**Comment by eRadical** [comment]
I didn't had any issue with this but it's more like making Ansible do the joining as Galera wants it.
Either way only one machine will reach first the first node it will be marked as donor and all others will block till it finishes.

Haven't tested what happens when you want to increase from 3 to 5 nodes in the cluster and you have some data (GB of them)... it's there where I think the difference would be obvious.

**Comment by mrlesmithjr** [comment]
That is a great point. I actually like that idea.
