### ISSUE TITLE
ubuntu24 fail install mariadb10.11 due to python-pymysql mising

### ISSUE THREAD

**Issue by FrancYescO** [mrlesmithjr/ansible-mariadb-galera-cluster#212]
just try to execute on ubuntu24 and requesting to install v10.11 of mariadb

fatal: [dbc03]: FAILED! => {"changed": false, "msg": "No package matching 'python-pymysql' is available"}
fatal: [dbc01]: FAILED! => {"changed": false, "msg": "No package matching 'python-pymysql' is available"}
fatal: [dbc02]: FAILED! => {"changed": false, "msg": "No package matching 'python-pymysql' is available"}

maybe is due to something wrong in official repos as also official install commands are failing:

```
# curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | sudo bash -s -- --mariadb-server-version="mariadb-10.11"
# [info] Checking for script prerequisites.
# [info] MariaDB Server version 10.11 is valid
# [info] Repository file successfully written to /etc/apt/sources.list.d/mariadb.list
# [info] Adding trusted package signing keys...
# [info] Running apt-get update...
E: The repository 'https://dlm.mariadb.com/repo/maxscale/latest/apt noble Release' does not have a Release file.
# [error] Failed to add trusted package signing keys
```

**Comment by FrancYescO** [comment]
seems i solved by:

setting `galera_enable_mariadb_repo: false` (ubuntu24 already have mariadb10.11 in apt while the official mariadb repos does not have ubuntu24....)

removing `python-pymysql` from mariadb_pre_req_packages (idk why this is installed in combo with `python3-pymysql`, i just leaved this alone and all worked flawlessy)

**Comment by gurudusty** [comment]
I just had this issue as well, it looks like vars/ubuntu-24.yml has not been added.
There is not an ubuntu.yml (I'm guessing there was a backwards compatibility for versions < 20) so when ubuntu-24 isn't found it will fall back to the debian.yml which includes the python-pymysql package in mariadb_pre_req_packages.

My workaround was to modify the role locally, duplicating vars/ubuntu-22.yml to vars/ubuntu-24.yml.

**Comment by elcomtik** [comment]
Feel free to create PR
