### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by wvelez6** [mrlesmithjr/ansible-mariadb-galera-cluster#215]
I am having an issue and pardon for my ignorance as I'm new to ansible, which currently is a hate/love relationship with ansible.

I am trying to deploy a 3 node galera cluster, all packages install just fine but the cluster wont start. Upon inspecting galera.cnf I notice the line wsrep_cluster_address="gcomm://{{ hostvars[inventory_hostname]['ansible_' + galera_cluster_bind_interface]['ipv4']['address'] }},{{ hostvars[inventory_hostname]['ansible_' + galera_cluster_bind_interface]['ipv4']['address'] }},{{ hostvars[inventory_hostname]['ansible_' + galera_cluster_bind_interface]['ipv4']['address'] }}", this is supposed to have a list of my hosts, correct?

I feel like I am missing something on either my host_vars or group_vars files.

Using ansible 9 and community.mysql 3.9.0.

Thanks for any help.

**Comment by eRadical** [comment]
Hi,

You need to set `galera_cluster_bind_interface` to the actual name of the interface from your machines. For example `eth0` if that is it.

**Comment by wvelez6** [comment]
@eRadical I do have set it up on my group_var/all.yml in my case is ens160, just for testing, I commented it out from group_vars and added to all 3 host_vars files and it still the same result.

**Comment by eRadical** [comment]
@wvelez6 - is this still on?
I do need more info.
