### ISSUE TITLE
Role fails when jinja2_native=True

### ISSUE THREAD

**Issue by mcpovel** [mrlesmithjr/ansible-mariadb-galera-cluster#225]
**Describe the bug**
When setting jinja2_native=True is set in ansible.cfg the role fails on several variables. First the repo key is converted from hex to decimal giving an invalid  key 17394431339541615064. 
Second the calculated port for galera_ist_recv_addr_port doews not work as string.
3rd the list galera_cluster_nodes contains the return "None" of append function for each host upfront of the actual node list.
This then fails with a hostvars['N'] not available.

**To Reproduce**
Set  jinja2_native=True in ansible.,cfg and try to apply playbook.

**Expected behavior**
The playbook using the role should work with either setting of  jinja2_native

Using ansible 9.1 and ansible core 2.16.1

**Comment by eRadical** [comment]
I might have some bandwidth to test this somewhere in the middle of November.

Meanwhile if you have a fix, feel free to create a PR.

**Comment by mcpovel** [comment]
Great, I am already trying to identify and work around some type issues.

**Comment by eRadical** [comment]
Closed via PR #232
