### ISSUE TITLE
Variable to change default datadir in my.cnf

### ISSUE THREAD

**Issue by achandel** [mrlesmithjr/ansible-mariadb-galera-cluster#27]
If you want to use a different data directory e.g. in case of using an EBS volume to store data. The /templates/etc/mysql/my.cnf.j2 should use a variable for datadir.

**Comment by mrlesmithjr** [comment]
@achandel Thanks for this. I have implemented this and you should be good to go now.

**Comment by achandel** [comment]
@mrlesmithjr Thanks for this

**Comment by mrlesmithjr** [comment]
@achandel No problem at all.

**Comment by mrlesmithjr** [comment]
@achandel Thanks for the great feedback. Definitely let me know how everything works out for your deployment. And definitely let me know if you find anything that can be improved.

**Comment by achandel** [comment]
The role does not work when an data directory different from /var/lib/mysql is specified e.g. mariadb/data. This is an issue when a fresh install of the mariadb is done. This is not required if you are making changed to an existing installation, in this case you just need to make changes in my.cnf

SOLUTION
----------------

Once the installation is complete you need to copy the contents of /var/lib/mysql to your data directory. I worked around by adding these two tasks in setup_cluster.yml just after the task setup_cluster | killing lingering mysql processes:

- name: debian | changing data directory permissions
  command: chown -R mysql:mysql "{{ mariadb_mysql_settings.datadir }}"
  when: mariadb_mysql_settings.datadir != '/var/lib/mysql'

- name: debian | copying files from default data directory
  synchronize:
    src: "/var/lib/mysql/"
    dest: "{{ mariadb_mysql_settings.datadir }}"
    archive: yes
  become: true
  delegate_to: "{{ inventory_hostname }}"
  when: mariadb_mysql_settings.datadir != '/var/lib/mysql'

**Comment by mrlesmithjr** [comment]
@eRadical Thoughts on this?

**Comment by eRadical** [comment]
I think this will be covered w/ the changes that I'll soon (hopefully very soon) send as per discussion in #29 
... and by that way you will not need to do the copy thing... the files will be generated from the beginning in that folder.

**Comment by mrlesmithjr** [comment]
Thanks for the input @eRadical. I tend to agree on the `synchronize` point as well.

**Comment by scuben** [comment]
I came across this issue today and got another solution without altering the role. Before executing the role I create a symlink to my real destination (mounted disk).

**Comment by madalinignisca** [comment]
Isn't it more simple to have a few tasks at start to ensure that datadir exists and it is owned by mysql user?

apt can use `policy_rc_d: 101` to not start on first node mariadb.

add mariadb configuration files, without galera confs

later when configuration files are currently put, only the galera ones are needed.

**Comment by gutleib** [comment]
Can confirm it's breaking a fresh install to non-standard folder
