### ISSUE TITLE
[WARNING]: Ignoring invalid attribute: serial

### ISSUE THREAD

**Issue by daledude** [mrlesmithjr/ansible-mariadb-galera-cluster#28]
ansible-playbook 2.6.3

I get this when trying to run the playbook:
[WARNING]: Ignoring invalid attribute: serial

**Comment by eRadical** [comment]
Yes.
I've seen this before.

It appears serial is no longer a per task option.
According to https://docs.ansible.com/ansible/2.6/user_guide/playbooks_strategies.html serial should be per play and must be declared as "strategy: serial" (I'm using mitogen_linear as strategy anyway)

Although it is benign... I think we can take it out.

**Comment by mrlesmithjr** [comment]
Awesome!

**Comment by daledude** [comment]
I saw ticket #21 regarding this and ended up removing it without issue.

Thanks guys!

**Comment by GrendelWWU** [comment]
Sorry for digging this out again. In some cases, it's important to serialize one special task, not the complete playbook. It would be running too long. I tried this with:
  - name: Patch einspielen
    strategy: single
    shell: "cd /test/bla && tar xvf /tmp/{{ patchfile }}"

But in tasks, single is ignored. I'm having problems, when this tar-command is running simultaneous on several machines, cause /test/bla may contain a symbolic link to a GPFS mounted device. The P stands for parallel, but then the execution is failing. I tried single:1, too, but it didn't work either. It's just ignored with a warning message, as reported by the original poster.

**Comment by eRadical** [comment]
@GrendelWWU  as I saw in https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html you can try the new `throttle: 1`.

Add it in the same place I once added `serial` and try it like that.
If it works ok... you're on the right track to a pull request! :)
