### ISSUE TITLE
debian | Python3 installing pre-reqs

### ISSUE THREAD

**Issue by achandel** [mrlesmithjr/ansible-mariadb-galera-cluster#31]
If you are using Python3 for ansible the following perquisites were required:
       - mysql-client
       - python3-dev
       - libmysqlclient-dev
       - python3-mysqldb
With the current role you can add it as your playbook (that uses this role) pre_task:

  pre_tasks:
    - name: Installing ansible pre-reqs for mariadb
      apt:
        name: "{{ item }}"
        state: present
      with_items:
       - python3-dev
       - mysql-client
       - libmysqlclient-dev
       - python3-mysqldb

python3-dev in case the remote machine does not have python installed.

**Comment by mrlesmithjr** [comment]
@achandel Did you figure out a way to add a conditional to check whether Python2 or Python3 is in use? That way we do not just throw down those packages when Python2 is in use. Maybe it doesn't really matter, but just a thought.
