### ISSUE TITLE
Various improvements

### ISSUE THREAD

**Issue by elcomtik** [mrlesmithjr/ansible-mariadb-galera-cluster#37]
I would like to add some features to the role:
- support for Centos8
- update default mariadb_version "10.1" to the latest "10.5"
- do some performance tuning to MySQL server conf by default (or suggest their usage in mariadb_config_overrides)
- add option to configure systemd timeout to start MariaDB service - this is necessary when DB sync on startup takes longer than default systemd timeout and creates restart loop
- add option to configure systems oom score to prevent killing service (what is very common if system has no swap, which is by the way bad practice for DB server)
- add option to configure TLS encrypted WSREP and SST communication

Most of the mentioned features I have already developed, it need only some refactoring and documentation. Would you accept such PRs?

**Comment by mrlesmithjr** [comment]
Absolutely!

**Comment by elcomtik** [comment]
Most of the above are currently solved. 

I will create PR for the rest soon:
- Systemd timeout to start 
- Performance tunning can be configured by

**Comment by elcomtik** [comment]
@mrlesmithjr I created some PRs for the features mentioned above, can you look at them and merge them eventually?

**Comment by elcomtik** [comment]
@mrlesmithjr thanks for merging. I'm closing this issue.
