### ISSUE TITLE
Bootstrapping galera cluster on Debian

### ISSUE THREAD

**Issue by DimitriSteyaert** [mrlesmithjr/ansible-mariadb-galera-cluster#5]
Hi, just wanted to let you know that I just used your module to deploy a Galera cluster on 3 Debian Jessie nodes but that I had to make a small modification to the file setup_cluster.yml in orde to get this working.

The next part contains validation only to allow the execution of galera_new_cluster on Ubuntu nodes:
```yaml
- name: setup_cluster | bootstrapping galera cluster
  command: "/usr/bin/galera_new_cluster"
  when: >
        not galera_cluster_configured.stat.exists and
        inventory_hostname == mysql_master_node and
        (ansible_distribution == "Ubuntu" and
        ansible_distribution_version >= '16.04')
```

So on my Debian Jessie servers this failed. 
Maybe change this part to
```yaml
- name: setup_cluster | bootstrapping galera cluster
  command: "/usr/bin/galera_new_cluster"
  when: >
        not galera_cluster_configured.stat.exists and
        inventory_hostname == mysql_master_node and
        ((ansible_distribution == "Ubuntu" and
        ansible_distribution_version >= '16.04') or
        ansible_distribution == "Debian")
```
which did it for me.
Cheers

**Comment by mrlesmithjr** [comment]
@DimitriSteyaert Thanks for the info. I have implemented that change. Thanks for the heads up!
