### ISSUE TITLE
Adding PyMySQL dependency

### ISSUE THREAD

**Issue by rutger1140** [mrlesmithjr/ansible-mariadb-galera-cluster#52]
When running a playbook (on Ubuntu 18 LTS) that sets the python_interpreter to `python3` before the `mariadb-galera-cluster` role I get this error:

```yaml
TASK [mariadb-galera-cluster : debian | adding debian-sys-maintenance permissions to mysql] *****************************************************************
System info:
  Ansible 2.10.3; Darwin
---------------------------------------------------
The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module
is required.
fatal: [xxx]: FAILED! => {"changed": false}
```

When adding `python3-pymysql` to the `vars/Debian.yml` -> `mariadb_pre_req_packages` it seems to work properly.

Solution found in [this](https://github.com/geerlingguy/ansible-role-mysql/issues/344) ansible-role-mysql issue.

**Comment by elcomtik** [comment]
@rutger1140 can you test it with the latest role version. It should be solved by https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/pull/56

**Comment by rutger1140** [comment]
@elcomtik Sorry for the delay, yes it works now. Thanks!

**Comment by elcomtik** [comment]
you are welcome
