### ISSUE TITLE
Remove support for ansible_distribution_version <= '14.04'

### ISSUE THREAD

**Issue by elcomtik** [mrlesmithjr/ansible-mariadb-galera-cluster#55]
In order to clean up code I suggest removal of support for Debian like ansible_distribution_version <= '14.04'

**Comment by elcomtik** [comment]
@mrlesmithjr do we want to persist vagrant configs or it can be removed?

**Comment by mrlesmithjr** [comment]
@elcomtik I am in favor of removing the Vagrant configs to move this forward in a more efficient manner.

**Comment by elcomtik** [comment]
Ok, I'll start working on it immediately. I have literally a ton of changes for this role, but a reliable test is necessary at first.

Could you please help me by giving the info asked here? https://github.com/mrlesmithjr/cookiecutter-ansible-role/issues/8. 

This would help me a lot. Thanks

**Comment by elcomtik** [comment]
Solved by https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/pull/56
