### ISSUE TITLE
Some additions that should be made to galera.cnf

### ISSUE THREAD

**Issue by techdaddies-kevin** [mrlesmithjr/ansible-mariadb-galera-cluster#6]
The official Galera deployment guidelines make a few recommendations that I'd love to see implemented into this playbook.

1. Each datacenter should have a unique gmcast.segment ID so that the nodes know who is closest and who is in each DC (Helps with replication optimization). It would be great to be able to define this in the host or group inventory.

2. Use the server private IP address in ist.recv_bind. This is optional, but it allows SSTs to complete faster as long as you have at least 2 servers in each location. Again, if we could configure this on a per-host basis in the inventory, that would be great.

3. Some way to enable encryption between the nodes would be very desirable. Setting up SSL protection between the nodes is actually very simple in Galera (http://galeracluster.com/documentation-webpages/ssl.html) and it would be great if this was included as part of this playbook.

4. Some way to define wsrep_node_address in the host vars. This setting is necessary in some environments where Galera can't properly guess the correct IP address to use due to NAT, multiple network cards, multiple nodes on a host, and some other situations.

This is a very nice piece of work. If I find some extra time, I will try to submit pull requests to implement these changes.

**Comment by mrlesmithjr** [comment]
@techdaddies-kevin Thanks for the great feedback. I have reorganized the variables for this role a bit to clean them up in preparation, of looking at implementing some of your recommendations. Very much appreciated.

**Comment by techdaddies-kevin** [comment]
Awesome! For what it's worth, I think the most important ones are 1 and 2 as these optimize traffic which is desired in a geodistributed cluster like mine. 3 was very easy to set up by simply introducing a new ssl.cnf file in the conf.d directory on our Ubuntu machines so I assume other users can do something similar easily if they desire SSL.

**Comment by mrlesmithjr** [comment]
@techdaddies-kevin I have implemented 3 of the 4 recommendations and have done some initial testing and these new settings seem to apply and work as expected but will need further testing for validation. Could you do some additional testing to confirm these options work as expected? If they do then I will merge these changes into MASTER.

**Comment by techdaddies-kevin** [comment]
I will spin up a few servers this weekend to double check, but at first glance this looks perfect!

**Comment by mrlesmithjr** [comment]
Sounds good. Just let me how it goes.

**Comment by techdaddies-kevin** [comment]
Seemed to work perfectly!

**Comment by mrlesmithjr** [comment]
@techdaddies-kevin Awesome. I will merge this and push up to MASTER.

**Comment by eRadical** [comment]
For nr.2 - This can work only in the same data-center. If I have some machines in a DC and some other in another DC this might end up in a mess.

I might find some time to do 1 & 2 but just want to check w/ you if the following is ok:

For 1:
[galera_cluster]
project-dev-galera-cluster-[1:3].example.com ...size=4gb region=nyc1 image=centos-7-x64... galera_ist_recv_bind_interface=ethX

This will use ansible_ethX.ipv4.address.

For 2:
[galera_cluster]
project-dev-galera-cluster-[1:3].example.com ...size=4gb region=nyc1 image=centos-7-x64... galera_gmcast_segment=1
project-dev-galera-cluster-4.example.com ...size=4gb region=nyc3 image=centos-7-x64... galera_gmcast_segment=2
project-dev-galera-cluster-5.example.com ...size=4gb region=sfo1 image=centos-7-x64... galera_gmcast_segment=3

Would that be ok?
I don't think they can be combined though...

**Comment by eRadical** [comment]
reopen
