### ISSUE TITLE
Don't print root password

### ISSUE THREAD

**Issue by techdaddies-kevin** [mrlesmithjr/ansible-mariadb-galera-cluster#7]
Consider using no_log: True to prevent outputting the root password when setting the root password

```
mrlesmithjr.mariadb-galera-cluster : mysql_root_pw | setting
skipping: [app1.domain.com] => (item={u'question': u'mysql-server/root_password', u'value': u'supersecurepasswordhere'})
```

**Comment by mrlesmithjr** [comment]
@techdaddies-kevin That is a great point. I will work on getting this implemented. Thanks!

**Comment by mrlesmithjr** [comment]
@techdaddies-kevin Implemented. Thanks for this.

**Comment by techdaddies-kevin** [comment]
Beautiful!
