### ISSUE TITLE
New cluster setup fails on CentOS 8 when using mariabackup for sst

### ISSUE THREAD

**Issue by eRadical** [mrlesmithjr/ansible-mariadb-galera-cluster#71]
**Describe the bug**
When setting up a new cluster from scratch on CentOS 8 (probably all CentOS and all RedHat) the cluster fails if using mariabackup for sst.

**To Reproduce**
Starting a new cluster on CentOS 8

**Error**
failed: [cluster-machine-1 -> cluster-machine-1] (item=[{'name': 'mariadb-sst', 'plugin': 'unix_socket', 'password': '..., 'priv': '*.*:RELOAD,PROCESS,LOCK TABLES,BINLOG MONITOR'}, 'localhost']) => {"ansible_loop_var": "item", "changed": false, "item": [{"name": "mariadb-sst", "password": "...", "plugin": "unix_socket", "priv": "*.*:RELOAD,PROCESS,LOCK TABLES,BINLOG MONITOR"}, "localhost"], "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (2002, \"Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)\")"}

**Additional context**
Most probably this was introduces in https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/commit/b1c69f32e8b84ca74c6c89ce3d310a05681f1880#diff-3d0ff1709ca48add100327bb2a468e6c508fb92a159c64c4f99ad1df89d9bdde by moving the users task above cluster setup. But on CentOS (and RedHat) the service is not started after install.

**Comment by eRadical** [comment]
I'll try to start MariaDB in [redhat.yaml ](https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/blob/master/tasks/redhat.yml) to make it even w/ Debian.

cc @mrlesmithjr @elcomtik

**Comment by elcomtik** [comment]
That is another issue which sliped through my manual testing. I teste it on working cluster by reconfiguring it. We would definitely appreciate some molecule test case for such setup. Thanks for feedback @eRadical

**Comment by eRadical** [comment]
The catch here is my old addition `overrides.cnf`.
This file must be placed before you start the server as it generates "ib data" & "ib logfiles".
Else it will generate the files w/ potentially different file size.
Thankfully this happening.

It worked ok for me. I already have one cluster up w/ my patch.
